# Generated by Django 5.2.6 on 2025-09-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("manager", "Менеджер"), ("moderator", "Модератор")],
                default="user",
                max_length=10,
                verbose_name="Роль",
            ),
        ),
    ]
