# Generated by Django 5.2.6 on 2025-09-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link_for_pay",
            field=models.URLField(
                blank=True,
                help_text="введите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссыллка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="введите id сессии", max_length=255, null=True, verbose_name="id сессии"
            ),
        ),
    ]
