# Generated by Django 5.2.5 on 2025-08-29 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название курса")),
                ("description", models.TextField(verbose_name="Описание курса")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение превьюшки курса",
                        null=True,
                        upload_to="courses/previews",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jfif", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Превьюшка курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "db_table": "Courses",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=300, verbose_name="Название урока")),
                ("description", models.TextField(verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение превьюшки урока",
                        null=True,
                        upload_to="lessons/previews",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jfif", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Превьюшка урока",
                    ),
                ),
                ("video_link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lms.course", verbose_name="Курс"
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "db_table": "lessons",
            },
        ),
    ]
