# Generated by Django 5.2.6 on 2025-09-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Автоматически обновляется при изменении курса",
                verbose_name="Дата последнего обновления",
            ),
        ),
    ]
