# Generated by Django 5.2.6 on 2025-09-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления"),
        ),
    ]
